package love.digimons.digi_applimobs.items;

import love.digimons.digi_applimobs.AppliUtils;
import love.digimons.digi_applimobs.blocks.BlockReg;
import love.digimons.digi_applimobs.entities.Rebooter;
import love.digimons.digi_applimobs.entities.VerUpItem;
import love.digimons.digi_applimobs.items.armors.*;
import love.digimons.digi_applimobs.items.tools.*;
import love.digimons.digi_applimobs.liq.FluidReg;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.BucketItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemReg {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, AppliUtils.MOD_ID);
    public static final RegistryObject<Item> appliIngot = ITEMS.register("appli_ingot", AppliNormalItem::new);

    public static final RegistryObject<Item> appliIngotNugget = ITEMS.register("appli_nugget", AppliNormalItem::new);

    public static final RegistryObject<Item> appliStick = ITEMS.register("appli_stick", AppliNormalItem::new);
    public static final RegistryObject<Item> gatch_monaka = ITEMS.register("gatch_monaka", GatchMonaka::new);
    public static final RegistryObject<Item> appliSword = ITEMS.register("appli_sword", AppliSword::new);
    public static final RegistryObject<Item> appliPickaxe = ITEMS.register("appli_pickaxe", AppliPickaxe::new);
    public static final RegistryObject<Item> appliAxe = ITEMS.register("appli_axe", AppliAxe::new);
    public static final RegistryObject<Item> appliShovel = ITEMS.register("appli_shovel", AppliShovel::new);
    public static final RegistryObject<Item> appliHelmet = ITEMS.register("appli_helmet", AppliHelmet::new);
    public static final RegistryObject<Item> appliChestPlate = ITEMS.register("appli_chestplate", AppliChestplate::new);
    public static final RegistryObject<Item> appliLeggings = ITEMS.register("appli_leggings", AppliLeggings::new);
    public static final RegistryObject<Item> appliBoots = ITEMS.register("appli_boots", AppliBoots::new);
    public static final RegistryObject<Item> fuminbHelmet = ITEMS.register("fuminb_helmet", FuminbHel::new);
    public static final RegistryObject<Item> applibow = ITEMS.register("appli_bow", AppliBow::new);

    public static final RegistryObject<Item> appliDrive = ITEMS.register("appli_drive", AppliDrive::new);
    public static final RegistryObject<Item> appliDriveDUO = ITEMS.register("appli_drive_duo", AppliDriveDUO::new);

    public static final RegistryObject<Item> batteryCS = ITEMS.register("btr_charger_s", ()-> new BatteryChargers((byte) 1));
    public static final RegistryObject<Item> batteryCM = ITEMS.register("btr_charger_m", ()-> new BatteryChargers((byte) 2));
    public static final RegistryObject<Item> batteryCL = ITEMS.register("btr_charger_l", ()-> new BatteryChargers((byte) 3));
    public static final RegistryObject<Item> batteryCX = ITEMS.register("btr_charger_x", ()-> new BatteryChargers((byte) 4));
    public static final RegistryObject<Item> batteryCMax = ITEMS.register("btr_charger_max", ()-> new BatteryChargers((byte) 5));
    public static final RegistryObject<Item> scrambleCode = ITEMS.register("scramble_code", ()-> new HissatuAddItem((byte)1));
    public static final RegistryObject<Item> scrambleCodeA = ITEMS.register("scramble_code_a", ()-> new HissatuAddItem((byte)2));
    public static final RegistryObject<Item> scrambleCodeX = ITEMS.register("scramble_code_x", ()-> new HissatuAddItem((byte)3));
    public static final RegistryObject<Item> memoryCleaner = ITEMS.register("mmr_cleaner", MemeryCleaner::new);
    public static final RegistryObject<Item> chipUnlocker = ITEMS.register("unlocker", Unlocker::new);
    public static final RegistryObject<Item> deckReboot = ITEMS.register("deck_reboot", Rebooter::new);
    public static final RegistryObject<Item> gashaTicket = ITEMS.register("gasha_ticket", ()-> new  GashaTicket(239,241));
    public static final RegistryObject<Item> chooGashaTicket = ITEMS.register("choo_gasha_ticket", ()-> new GashaTicket(29,39));
    public static final RegistryObject<Item> kyooGashaTicket = ITEMS.register("kyoo_gasha_ticket", ()-> new GashaTicket(-1,199));
    public static final RegistryObject<Item> virusProgram = ITEMS.register("virus_prog", VirusProgram::new);
    public static final RegistryObject<Item> vaccineProgram = ITEMS.register("vaccine_prog", VacProgram::new);
    public static final RegistryObject<Item> versionUpPunch = ITEMS.register("version_up_punch", VerUpItem::new);
    public static final RegistryObject<Item> socialPatch = ITEMS.register("soc_patch", ()->new AtrriPatch((byte) 0));
    public static final RegistryObject<Item> naviPatch = ITEMS.register("navi_patch", ()->new AtrriPatch((byte) 1));
    public static final RegistryObject<Item> systemPatch = ITEMS.register("system_patch", ()->new AtrriPatch((byte) 6));
    public static final RegistryObject<Item> entaPatch = ITEMS.register("enta_patch", ()->new AtrriPatch((byte) 3));
    public static final RegistryObject<Item> livePatch = ITEMS.register("liv_patch", ()->new AtrriPatch((byte) 4));
    public static final RegistryObject<Item> toolPatch = ITEMS.register("tool_patch", ()->new AtrriPatch((byte) 5));
    public static final RegistryObject<Item> gamePatch = ITEMS.register("gam_patch", ()->new AtrriPatch((byte) 2));
    public static final RegistryObject<Item> antiSocial = ITEMS.register("anti_soc", ()->new AntiAttriItem((byte) 0));
    public static final RegistryObject<Item> antiNavi = ITEMS.register("anti_navi", ()->new AntiAttriItem((byte) 1));
    public static final RegistryObject<Item> antiSystem = ITEMS.register("anti_sys", ()->new AntiAttriItem((byte) 6));
    public static final RegistryObject<Item> antiEnta = ITEMS.register("anti_enta", ()->new AntiAttriItem((byte) 3));
    public static final RegistryObject<Item> antiLive = ITEMS.register("anti_liv", ()->new AntiAttriItem((byte) 4));
    public static final RegistryObject<Item> antiTool = ITEMS.register("anti_tool", ()->new AntiAttriItem((byte) 5));
    public static final RegistryObject<Item> antiGame = ITEMS.register("anti_gam", ()->new AntiAttriItem((byte) 2));
    public static final RegistryObject<Item> dataLabTicket = ITEMS.register("data_lab_ticket", DataLabTicket::new);
    public static final RegistryObject<Item> crepePie = ITEMS.register("crepe", CrepePie::new);
    public static final RegistryObject<Item> grepeOrGrape = ITEMS.register("grepe", GrepePie::new);
    public static final RegistryObject<Item> hpChargerS = ITEMS.register("hp_charger_s", ()-> new HPCharger((byte) 1));
    public static final RegistryObject<Item> hpChargerM = ITEMS.register("hp_charger_m", ()-> new HPCharger((byte) 2));
    public static final RegistryObject<Item> hpChargerL = ITEMS.register("hp_charger_l", ()-> new HPCharger((byte) 3));
    public static final RegistryObject<Item> hpFullCharger = ITEMS.register("hp_full_charger", ()-> new HPCharger((byte) 4));
    public static final RegistryObject<Item> powerTrainerXXS = ITEMS.register("power_trainer_xxs", ()->new PowerTrainer((byte) 1));
    public static final RegistryObject<Item> powerTrainerXS = ITEMS.register("power_trainer_xs", ()->new PowerTrainer((byte) 2));
    public static final RegistryObject<Item> powerTrainerS = ITEMS.register("power_trainer_s", ()->new PowerTrainer((byte) 3));
    public static final RegistryObject<Item> tapmonRetizer = ITEMS.register("tapmon_retizer", ()->new Retizer(new Item.Properties(),(byte) 1));
    public static final RegistryObject<Item> swipemonRetizer = ITEMS.register("swipemon_retizer", ()->new Retizer(new Item.Properties(),(byte) 2));
    public static final RegistryObject<Item> flickmonRetizer = ITEMS.register("flickmon_retizer", ()->new Retizer(new Item.Properties(),(byte) 0));
    public static final RegistryObject<Item> nazoPiece = ITEMS.register("nazo_piece", ()-> new AppliNormalItem(new Item.Properties().fireResistant()));
    public static RegistryObject<Item> NetFluidBucket = ITEMS.register("net_liq_bucket",
            () -> new BucketItem(FluidReg.stillANW, new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1)));

    public static final RegistryObject<Item> appliBlock =
            ITEMS.register("appli_block",
                    ()->new BlockItem(BlockReg.appliBlock.get(), new Item.Properties()));
    public static final RegistryObject<Item> appliOre =
            ITEMS.register("appli_ore",
                    ()->new BlockItem(BlockReg.appliOre.get(), new Item.Properties()));

    public static final RegistryObject<Item> appliFloor =
            ITEMS.register("appli_floor",
                    ()->new BlockItem(BlockReg.appliFloor.get(), new Item.Properties()));

    public static final RegistryObject<AppliChipItem> appliChipGatchmob = ITEMS.register("applichip_gatchmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCallmob = ITEMS.register("applichip_callmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMailmob = ITEMS.register("applichip_mailmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTubumob = ITEMS.register("applichip_tubumob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGengomob = ITEMS.register("applichip_gengomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipAddmob = ITEMS.register("applichip_addmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipReviewmob = ITEMS.register("applichip_reviewmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSetmob = ITEMS.register("applichip_setmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMessemob = ITEMS.register("applichip_messemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGugumob = ITEMS.register("applichip_gugumob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipKosomob = ITEMS.register("applichip_kosomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDogatchmob = ITEMS.register("applichip_dogatchmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSociamob = ITEMS.register("applichip_sociamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGossipmob = ITEMS.register("applichip_gossipmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSukasimob = ITEMS.register("applichip_sukasimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipLogimob = ITEMS.register("applichip_logimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipLogamob = ITEMS.register("applichip_logamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGlobemob = ITEMS.register("applichip_globemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCharismob = ITEMS.register("applichip_charismob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDamedamob = ITEMS.register("applichip_damedamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRocketmob = ITEMS.register("applichip_rocketmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipNavimob = ITEMS.register("applichip_navimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipJetmob = ITEMS.register("applichip_jetmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipWeathermob = ITEMS.register("applichip_weathermob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCompassmob = ITEMS.register("applichip_compassmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipYadomob = ITEMS.register("applichip_yadomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipNewsmob = ITEMS.register("applichip_newsmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTutomob = ITEMS.register("applichip_tutomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMcmob = ITEMS.register("applichip_mcmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipResshamob = ITEMS.register("applichip_resshamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSpeciamob = ITEMS.register("applichip_speciamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTripmob = ITEMS.register("applichip_tripmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipWeatherdramob = ITEMS.register("applichip_weatherdramob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSateramob = ITEMS.register("applichip_sateramob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCometmob = ITEMS.register("applichip_cometmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipProtecmob = ITEMS.register("applichip_protecmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipHackmob = ITEMS.register("applichip_hackmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipBatterimob = ITEMS.register("applichip_batterimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipPekomob = ITEMS.register("applichip_pekomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipPokomob = ITEMS.register("applichip_pokomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCopipemob = ITEMS.register("applichip_copipemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSavemob = ITEMS.register("applichip_savemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipKabemob = ITEMS.register("applichip_kabemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipEcomob = ITEMS.register("applichip_ecomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipPipomob = ITEMS.register("applichip_pipomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRaidramob = ITEMS.register("applichip_raidramob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDezipmob = ITEMS.register("applichip_dezipmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMienumob = ITEMS.register("applichip_mienumob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipWarpmob = ITEMS.register("applichip_warpmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDenpamob = ITEMS.register("applichip_denpamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSupermob = ITEMS.register("applichip_supermob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRevivemob = ITEMS.register("applichip_revivemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipWarudamob = ITEMS.register("applichip_warudamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDrawmob = ITEMS.register("applichip_drawmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTellermob = ITEMS.register("applichip_tellermob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMusimob = ITEMS.register("applichip_musimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipPerorimob = ITEMS.register("applichip_perorimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDressmob = ITEMS.register("applichip_dressmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipBookmob = ITEMS.register("applichip_bookmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGashamob = ITEMS.register("applichip_gashamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipLuckmob = ITEMS.register("applichip_luckmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTrickmob = ITEMS.register("applichip_trickmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDicemob = ITEMS.register("applichip_dicemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCookmob = ITEMS.register("applichip_cookmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDogamob = ITEMS.register("applichip_dogamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipEffecmob = ITEMS.register("applichip_effecmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipJumpplusmob = ITEMS.register("applichip_jumpplusmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTarotmob = ITEMS.register("applichip_tarotmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCoordemob = ITEMS.register("applichip_coordemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMediamob = ITEMS.register("applichip_mediamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipVegasmob = ITEMS.register("applichip_vegasmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDreamob = ITEMS.register("applichip_dreammob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSantamob = ITEMS.register("applichip_santamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipEntermob = ITEMS.register("applichip_entermob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSleepmob = ITEMS.register("applichip_sleepmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMusclemob = ITEMS.register("applichip_musclemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipAidmob = ITEMS.register("applichip_aidmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMoneymob = ITEMS.register("applichip_moneymob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSpamob = ITEMS.register("applichip_spamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSupplemob = ITEMS.register("applichip_supplemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDopemob = ITEMS.register("applichip_dopemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipAuctiomob = ITEMS.register("applichip_auctiomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipKakeimob = ITEMS.register("applichip_kakeimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipKaimob = ITEMS.register("applichip_kaimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipJishomob = ITEMS.register("applichip_jishomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipVirusmob = ITEMS.register("applichip_virusmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMedicmob = ITEMS.register("applichip_medicmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDocmob = ITEMS.register("applichip_docmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipConsulmob = ITEMS.register("applichip_consulmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipLibramob = ITEMS.register("applichip_libramob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipBiomob = ITEMS.register("applichip_biomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipBeautymob = ITEMS.register("applichip_beautymob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCameramob = ITEMS.register("applichip_cameramob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRecomob = ITEMS.register("applichip_recomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCalcumob = ITEMS.register("applichip_calcumob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGomimob = ITEMS.register("applichip_gomimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipMirrormob = ITEMS.register("applichip_mirrormob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipLightmob = ITEMS.register("applichip_lightmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipWatchmob = ITEMS.register("applichip_watchmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDiarimob = ITEMS.register("applichip_diarimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCalendamob = ITEMS.register("applichip_calendamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipOnpamob = ITEMS.register("applichip_onpamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipJammingmob = ITEMS.register("applichip_jammingmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTimemob = ITEMS.register("applichip_timemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRoamob = ITEMS.register("applichip_roamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipScorpmob = ITEMS.register("applichip_scorpmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCraftmob = ITEMS.register("applichip_craftmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipFakemob = ITEMS.register("applichip_fakemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipBootmob = ITEMS.register("applichip_bootmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipShutmob = ITEMS.register("applichip_shutmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDokamob = ITEMS.register("applichip_dokamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipShotmob = ITEMS.register("applichip_shotmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCardmob = ITEMS.register("applichip_cardmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRopuremob = ITEMS.register("applichip_ropuremob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipPuzzlemob = ITEMS.register("applichip_puzzlemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDancemob = ITEMS.register("applichip_dancemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRacemob = ITEMS.register("applichip_racemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipOnmob = ITEMS.register("applichip_onmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipOffmob = ITEMS.register("applichip_offmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipV_jumpmob = ITEMS.register("applichip_vjumpmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDosukomob = ITEMS.register("applichip_dosukomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipBramob = ITEMS.register("applichip_bramob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipCoachmob = ITEMS.register("applichip_coachmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipGaiamob = ITEMS.register("applichip_gaiamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipOujamob = ITEMS.register("applichip_oujamob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSakusimob = ITEMS.register("applichip_sakusimob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipUratekumob = ITEMS.register("applichip_uratekumob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipHadesmob = ITEMS.register("applichip_hadesmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipPoseidomob = ITEMS.register("applichip_poseidomob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipRebootmob = ITEMS.register("applichip_rebootmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDeusumob = ITEMS.register("applichip_deusumob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipOuranosmob = ITEMS.register("applichip_ouranosmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipDantemob = ITEMS.register("applichip_dantemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipFlickmob = ITEMS.register("applichip_flickmob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipSwipemob = ITEMS.register("applichip_swipemob",AppliChipItem::new);
    public static final RegistryObject<AppliChipItem> appliChipTapmob = ITEMS.register("applichip_tapmob",AppliChipItem::new);


    public static final RegistryObject<Item> appliUnlockedChipGatchmob = ITEMS.register("applichip_gatchmob_unlocked",()-> new AppliUnlockedChipItem(appliChipGatchmob));
    public static final RegistryObject<Item> appliUnlockedChipCallmob = ITEMS.register("applichip_callmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCallmob));
    public static final RegistryObject<Item> appliUnlockedChipMailmob = ITEMS.register("applichip_mailmob_unlocked",()-> new AppliUnlockedChipItem(appliChipMailmob));
    public static final RegistryObject<Item> appliUnlockedChipTubumob = ITEMS.register("applichip_tubumob_unlocked",()-> new AppliUnlockedChipItem(appliChipTubumob));
    public static final RegistryObject<Item> appliUnlockedChipGengomob = ITEMS.register("applichip_gengomob_unlocked",()-> new AppliUnlockedChipItem(appliChipGengomob));
    public static final RegistryObject<Item> appliUnlockedChipAddmob = ITEMS.register("applichip_addmob_unlocked",()-> new AppliUnlockedChipItem(appliChipAddmob));
    public static final RegistryObject<Item> appliUnlockedChipReviewmob = ITEMS.register("applichip_reviewmob_unlocked",()-> new AppliUnlockedChipItem(appliChipReviewmob));
    public static final RegistryObject<Item> appliUnlockedChipSetmob = ITEMS.register("applichip_setmob_unlocked",()-> new AppliUnlockedChipItem(appliChipSetmob));
    public static final RegistryObject<Item> appliUnlockedChipMessemob = ITEMS.register("applichip_messemob_unlocked",()-> new AppliUnlockedChipItem(appliChipMessemob));
    public static final RegistryObject<Item> appliUnlockedChipGugumob = ITEMS.register("applichip_gugumob_unlocked",()-> new AppliUnlockedChipItem(appliChipGugumob));
    public static final RegistryObject<Item> appliUnlockedChipKosomob = ITEMS.register("applichip_kosomob_unlocked",()-> new AppliUnlockedChipItem(appliChipKosomob));
    public static final RegistryObject<Item> appliUnlockedChipDogatchmob = ITEMS.register("applichip_dogatchmob_unlocked",()-> new AppliUnlockedChipItem(appliChipDogatchmob));
    public static final RegistryObject<Item> appliUnlockedChipSociamob = ITEMS.register("applichip_sociamob_unlocked",()-> new AppliUnlockedChipItem(appliChipSociamob));
    public static final RegistryObject<Item> appliUnlockedChipGossipmob = ITEMS.register("applichip_gossipmob_unlocked",()-> new AppliUnlockedChipItem(appliChipGossipmob));
    public static final RegistryObject<Item> appliUnlockedChipSukasimob = ITEMS.register("applichip_sukasimob_unlocked",()-> new AppliUnlockedChipItem(appliChipSukasimob));
    public static final RegistryObject<Item> appliUnlockedChipLogimob = ITEMS.register("applichip_logimob_unlocked",()-> new AppliUnlockedChipItem(appliChipLogimob));
    public static final RegistryObject<Item> appliUnlockedChipLogamob = ITEMS.register("applichip_logamob_unlocked",()-> new AppliUnlockedChipItem(appliChipLogamob));
    public static final RegistryObject<Item> appliUnlockedChipGlobemob = ITEMS.register("applichip_globemob_unlocked",()-> new AppliUnlockedChipItem(appliChipGlobemob));
    public static final RegistryObject<Item> appliUnlockedChipCharismob = ITEMS.register("applichip_charismob_unlocked",()-> new AppliUnlockedChipItem(appliChipCharismob));
    public static final RegistryObject<Item> appliUnlockedChipDamedamob = ITEMS.register("applichip_damedamob_unlocked",()-> new AppliUnlockedChipItem(appliChipDamedamob));
    public static final RegistryObject<Item> appliUnlockedChipRocketmob = ITEMS.register("applichip_rocketmob_unlocked",()-> new AppliUnlockedChipItem(appliChipRocketmob));
    public static final RegistryObject<Item> appliUnlockedChipNavimob = ITEMS.register("applichip_navimob_unlocked",()-> new AppliUnlockedChipItem(appliChipNavimob));
    public static final RegistryObject<Item> appliUnlockedChipJetmob = ITEMS.register("applichip_jetmob_unlocked",()-> new AppliUnlockedChipItem(appliChipJetmob));
    public static final RegistryObject<Item> appliUnlockedChipWeathermob = ITEMS.register("applichip_weathermob_unlocked",()-> new AppliUnlockedChipItem(appliChipWeathermob));
    public static final RegistryObject<Item> appliUnlockedChipCompassmob = ITEMS.register("applichip_compassmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCompassmob));
    public static final RegistryObject<Item> appliUnlockedChipYadomob = ITEMS.register("applichip_yadomob_unlocked",()-> new AppliUnlockedChipItem(appliChipYadomob));
    public static final RegistryObject<Item> appliUnlockedChipNewsmob = ITEMS.register("applichip_newsmob_unlocked",()-> new AppliUnlockedChipItem(appliChipNewsmob));
    public static final RegistryObject<Item> appliUnlockedChipTutomob = ITEMS.register("applichip_tutomob_unlocked",()-> new AppliUnlockedChipItem(appliChipTutomob));
    public static final RegistryObject<Item> appliUnlockedChipMcmob = ITEMS.register("applichip_mcmob_unlocked",()-> new AppliUnlockedChipItem(appliChipMcmob));
    public static final RegistryObject<Item> appliUnlockedChipResshamob = ITEMS.register("applichip_resshamob_unlocked",()-> new AppliUnlockedChipItem(appliChipResshamob));
    public static final RegistryObject<Item> appliUnlockedChipSpeciamob = ITEMS.register("applichip_speciamob_unlocked",()-> new AppliUnlockedChipItem(appliChipSpeciamob));
    public static final RegistryObject<Item> appliUnlockedChipTripmob = ITEMS.register("applichip_tripmob_unlocked",()-> new AppliUnlockedChipItem(appliChipTripmob));
    public static final RegistryObject<Item> appliUnlockedChipWeatherdramob = ITEMS.register("applichip_weatherdramob_unlocked",()-> new AppliUnlockedChipItem(appliChipWeatherdramob));
    public static final RegistryObject<Item> appliUnlockedChipSateramob = ITEMS.register("applichip_sateramob_unlocked",()-> new AppliUnlockedChipItem(appliChipSateramob));
    public static final RegistryObject<Item> appliUnlockedChipCometmob = ITEMS.register("applichip_cometmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCometmob));
    public static final RegistryObject<Item> appliUnlockedChipProtecmob = ITEMS.register("applichip_protecmob_unlocked",()-> new AppliUnlockedChipItem(appliChipProtecmob));
    public static final RegistryObject<Item> appliUnlockedChipHackmob = ITEMS.register("applichip_hackmob_unlocked",()-> new AppliUnlockedChipItem(appliChipHackmob));
    public static final RegistryObject<Item> appliUnlockedChipBatterimob = ITEMS.register("applichip_batterimob_unlocked",()-> new AppliUnlockedChipItem(appliChipBatterimob));
    public static final RegistryObject<Item> appliUnlockedChipPekomob = ITEMS.register("applichip_pekomob_unlocked",()-> new AppliUnlockedChipItem(appliChipPekomob));
    public static final RegistryObject<Item> appliUnlockedChipPokomob = ITEMS.register("applichip_pokomob_unlocked",()-> new AppliUnlockedChipItem(appliChipPokomob));
    public static final RegistryObject<Item> appliUnlockedChipCopipemob = ITEMS.register("applichip_copipemob_unlocked",()-> new AppliUnlockedChipItem(appliChipCopipemob));
    public static final RegistryObject<Item> appliUnlockedChipSavemob = ITEMS.register("applichip_savemob_unlocked",()-> new AppliUnlockedChipItem(appliChipSavemob));
    public static final RegistryObject<Item> appliUnlockedChipKabemob = ITEMS.register("applichip_kabemob_unlocked",()-> new AppliUnlockedChipItem(appliChipKabemob));
    public static final RegistryObject<Item> appliUnlockedChipEcomob = ITEMS.register("applichip_ecomob_unlocked",()-> new AppliUnlockedChipItem(appliChipEcomob));
    public static final RegistryObject<Item> appliUnlockedChipPipomob = ITEMS.register("applichip_pipomob_unlocked",()-> new AppliUnlockedChipItem(appliChipPipomob));
    public static final RegistryObject<Item> appliUnlockedChipRaidramob = ITEMS.register("applichip_raidramob_unlocked",()-> new AppliUnlockedChipItem(appliChipRaidramob));
    public static final RegistryObject<Item> appliUnlockedChipDezipmob = ITEMS.register("applichip_dezipmob_unlocked",()-> new AppliUnlockedChipItem(appliChipDezipmob));
    public static final RegistryObject<Item> appliUnlockedChipMienumob = ITEMS.register("applichip_mienumob_unlocked",()-> new AppliUnlockedChipItem(appliChipMienumob));
    public static final RegistryObject<Item> appliUnlockedChipWarpmob = ITEMS.register("applichip_warpmob_unlocked",()-> new AppliUnlockedChipItem(appliChipWarpmob));
    public static final RegistryObject<Item> appliUnlockedChipDenpamob = ITEMS.register("applichip_denpamob_unlocked",()-> new AppliUnlockedChipItem(appliChipDenpamob));
    public static final RegistryObject<Item> appliUnlockedChipSupermob = ITEMS.register("applichip_supermob_unlocked",()-> new AppliUnlockedChipItem(appliChipSupermob));
    public static final RegistryObject<Item> appliUnlockedChipRevivemob = ITEMS.register("applichip_revivemob_unlocked",()-> new AppliUnlockedChipItem(appliChipRevivemob));
    public static final RegistryObject<Item> appliUnlockedChipWarudamob = ITEMS.register("applichip_warudamob_unlocked",()-> new AppliUnlockedChipItem(appliChipWarudamob));
    public static final RegistryObject<Item> appliUnlockedChipDrawmob = ITEMS.register("applichip_drawmob_unlocked",()-> new AppliUnlockedChipItem(appliChipDrawmob));
    public static final RegistryObject<Item> appliUnlockedChipTellermob = ITEMS.register("applichip_tellermob_unlocked",()-> new AppliUnlockedChipItem(appliChipTellermob));
    public static final RegistryObject<Item> appliUnlockedChipMusimob = ITEMS.register("applichip_musimob_unlocked",()-> new AppliUnlockedChipItem(appliChipMusimob));
    public static final RegistryObject<Item> appliUnlockedChipPerorimob = ITEMS.register("applichip_perorimob_unlocked",()-> new AppliUnlockedChipItem(appliChipPerorimob));
    public static final RegistryObject<Item> appliUnlockedChipDressmob = ITEMS.register("applichip_dressmob_unlocked",()-> new AppliUnlockedChipItem(appliChipDressmob));
    public static final RegistryObject<Item> appliUnlockedChipBookmob = ITEMS.register("applichip_bookmob_unlocked",()-> new AppliUnlockedChipItem(appliChipBookmob));
    public static final RegistryObject<Item> appliUnlockedChipGashamob = ITEMS.register("applichip_gashamob_unlocked",()-> new AppliUnlockedChipItem(appliChipGashamob));
    public static final RegistryObject<Item> appliUnlockedChipLuckmob = ITEMS.register("applichip_luckmob_unlocked",()-> new AppliUnlockedChipItem(appliChipLuckmob));
    public static final RegistryObject<Item> appliUnlockedChipTrickmob = ITEMS.register("applichip_trickmob_unlocked",()-> new AppliUnlockedChipItem(appliChipTrickmob));
    public static final RegistryObject<Item> appliUnlockedChipDicemob = ITEMS.register("applichip_dicemob_unlocked",()-> new AppliUnlockedChipItem(appliChipDicemob));
    public static final RegistryObject<Item> appliUnlockedChipCookmob = ITEMS.register("applichip_cookmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCookmob));
    public static final RegistryObject<Item> appliUnlockedChipDogamob = ITEMS.register("applichip_dogamob_unlocked",()-> new AppliUnlockedChipItem(appliChipDogamob));
    public static final RegistryObject<Item> appliUnlockedChipEffecmob = ITEMS.register("applichip_effecmob_unlocked",()-> new AppliUnlockedChipItem(appliChipEffecmob));
    public static final RegistryObject<Item> appliUnlockedChipJumpplusmob = ITEMS.register("applichip_jumpplusmob_unlocked",()-> new AppliUnlockedChipItem(appliChipJumpplusmob));
    public static final RegistryObject<Item> appliUnlockedChipTarotmob = ITEMS.register("applichip_tarotmob_unlocked",()-> new AppliUnlockedChipItem(appliChipTarotmob));
    public static final RegistryObject<Item> appliUnlockedChipCoordemob = ITEMS.register("applichip_coordemob_unlocked",()-> new AppliUnlockedChipItem(appliChipCoordemob));
    public static final RegistryObject<Item> appliUnlockedChipMediamob = ITEMS.register("applichip_mediamob_unlocked",()-> new AppliUnlockedChipItem(appliChipMediamob));
    public static final RegistryObject<Item> appliUnlockedChipVegasmob = ITEMS.register("applichip_vegasmob_unlocked",()-> new AppliUnlockedChipItem(appliChipVegasmob));
    public static final RegistryObject<Item> appliUnlockedChipDreamob = ITEMS.register("applichip_dreammob_unlocked",()-> new AppliUnlockedChipItem(appliChipDreamob));
    public static final RegistryObject<Item> appliUnlockedChipSantamob = ITEMS.register("applichip_santamob_unlocked",()-> new AppliUnlockedChipItem(appliChipSantamob));
    public static final RegistryObject<Item> appliUnlockedChipEntermob = ITEMS.register("applichip_entermob_unlocked",()-> new AppliUnlockedChipItem(appliChipEntermob));
    public static final RegistryObject<Item> appliUnlockedChipSleepmob = ITEMS.register("applichip_sleepmob_unlocked",()-> new AppliUnlockedChipItem(appliChipSleepmob));
    public static final RegistryObject<Item> appliUnlockedChipMusclemob = ITEMS.register("applichip_musclemob_unlocked",()-> new AppliUnlockedChipItem(appliChipMusclemob));
    public static final RegistryObject<Item> appliUnlockedChipAidmob = ITEMS.register("applichip_aidmob_unlocked",()-> new AppliUnlockedChipItem(appliChipAidmob));
    public static final RegistryObject<Item> appliUnlockedChipMoneymob = ITEMS.register("applichip_moneymob_unlocked",()-> new AppliUnlockedChipItem(appliChipMoneymob));
    public static final RegistryObject<Item> appliUnlockedChipSpamob = ITEMS.register("applichip_spamob_unlocked",()-> new AppliUnlockedChipItem(appliChipSpamob));
    public static final RegistryObject<Item> appliUnlockedChipSupplemob = ITEMS.register("applichip_supplemob_unlocked",()-> new AppliUnlockedChipItem(appliChipSupplemob));
    public static final RegistryObject<Item> appliUnlockedChipDopemob = ITEMS.register("applichip_dopemob_unlocked",()-> new AppliUnlockedChipItem(appliChipDopemob));
    public static final RegistryObject<Item> appliUnlockedChipAuctiomob = ITEMS.register("applichip_auctiomob_unlocked",()-> new AppliUnlockedChipItem(appliChipAuctiomob));
    public static final RegistryObject<Item> appliUnlockedChipKakeimob = ITEMS.register("applichip_kakeimob_unlocked",()-> new AppliUnlockedChipItem(appliChipKakeimob));
    public static final RegistryObject<Item> appliUnlockedChipKaimob = ITEMS.register("applichip_kaimob_unlocked",()-> new AppliUnlockedChipItem(appliChipKaimob));
    public static final RegistryObject<Item> appliUnlockedChipJishomob = ITEMS.register("applichip_jishomob_unlocked",()-> new AppliUnlockedChipItem(appliChipJishomob));
    public static final RegistryObject<Item> appliUnlockedChipVirusmob = ITEMS.register("applichip_virusmob_unlocked",()-> new AppliUnlockedChipItem(appliChipVirusmob));
    public static final RegistryObject<Item> appliUnlockedChipMedicmob = ITEMS.register("applichip_medicmob_unlocked",()-> new AppliUnlockedChipItem(appliChipMedicmob));
    public static final RegistryObject<Item> appliUnlockedChipDocmob = ITEMS.register("applichip_docmob_unlocked",()-> new AppliUnlockedChipItem(appliChipDocmob));
    public static final RegistryObject<Item> appliUnlockedChipConsulmob = ITEMS.register("applichip_consulmob_unlocked",()-> new AppliUnlockedChipItem(appliChipConsulmob));
    public static final RegistryObject<Item> appliUnlockedChipLibramob = ITEMS.register("applichip_libramob_unlocked",()-> new AppliUnlockedChipItem(appliChipLibramob));
    public static final RegistryObject<Item> appliUnlockedChipBiomob = ITEMS.register("applichip_biomob_unlocked",()-> new AppliUnlockedChipItem(appliChipBiomob));
    public static final RegistryObject<Item> appliUnlockedChipBeautymob = ITEMS.register("applichip_beautymob_unlocked",()-> new AppliUnlockedChipItem(appliChipBeautymob));
    public static final RegistryObject<Item> appliUnlockedChipCameramob = ITEMS.register("applichip_cameramob_unlocked",()-> new AppliUnlockedChipItem(appliChipCameramob));
    public static final RegistryObject<Item> appliUnlockedChipRecomob = ITEMS.register("applichip_recomob_unlocked",()-> new AppliUnlockedChipItem(appliChipRecomob));
    public static final RegistryObject<Item> appliUnlockedChipCalcumob = ITEMS.register("applichip_calcumob_unlocked",()-> new AppliUnlockedChipItem(appliChipCalcumob));
    public static final RegistryObject<Item> appliUnlockedChipGomimob = ITEMS.register("applichip_gomimob_unlocked",()-> new AppliUnlockedChipItem(appliChipGomimob));
    public static final RegistryObject<Item> appliUnlockedChipMirrormob = ITEMS.register("applichip_mirrormob_unlocked",()-> new AppliUnlockedChipItem(appliChipMirrormob));
    public static final RegistryObject<Item> appliUnlockedChipLightmob = ITEMS.register("applichip_lightmob_unlocked",()-> new AppliUnlockedChipItem(appliChipLightmob));
    public static final RegistryObject<Item> appliUnlockedChipWatchmob = ITEMS.register("applichip_watchmob_unlocked",()-> new AppliUnlockedChipItem(appliChipWatchmob));
    public static final RegistryObject<Item> appliUnlockedChipDiarimob = ITEMS.register("applichip_diarimob_unlocked",()-> new AppliUnlockedChipItem(appliChipDiarimob));
    public static final RegistryObject<Item> appliUnlockedChipCalendamob = ITEMS.register("applichip_calendamob_unlocked",()-> new AppliUnlockedChipItem(appliChipCalendamob));
    public static final RegistryObject<Item> appliUnlockedChipOnpamob = ITEMS.register("applichip_onpamob_unlocked",()-> new AppliUnlockedChipItem(appliChipOnpamob));
    public static final RegistryObject<Item> appliUnlockedChipJammingmob = ITEMS.register("applichip_jammingmob_unlocked",()-> new AppliUnlockedChipItem(appliChipJammingmob));
    public static final RegistryObject<Item> appliUnlockedChipTimemob = ITEMS.register("applichip_timemob_unlocked",()-> new AppliUnlockedChipItem(appliChipTimemob));
    public static final RegistryObject<Item> appliUnlockedChipRoamob = ITEMS.register("applichip_roamob_unlocked",()-> new AppliUnlockedChipItem(appliChipRoamob));
    public static final RegistryObject<Item> appliUnlockedChipScorpmob = ITEMS.register("applichip_scorpmob_unlocked",()-> new AppliUnlockedChipItem(appliChipScorpmob));
    public static final RegistryObject<Item> appliUnlockedChipCraftmob = ITEMS.register("applichip_craftmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCraftmob));
    public static final RegistryObject<Item> appliUnlockedChipFakemob = ITEMS.register("applichip_fakemob_unlocked",()-> new AppliUnlockedChipItem(appliChipFakemob));
    public static final RegistryObject<Item> appliUnlockedChipBootmob = ITEMS.register("applichip_bootmob_unlocked",()-> new AppliUnlockedChipItem(appliChipBootmob));
    public static final RegistryObject<Item> appliUnlockedChipShutmob = ITEMS.register("applichip_shutmob_unlocked",()-> new AppliUnlockedChipItem(appliChipShutmob));
    public static final RegistryObject<Item> appliUnlockedChipDokamob = ITEMS.register("applichip_dokamob_unlocked",()-> new AppliUnlockedChipItem(appliChipDokamob));
    public static final RegistryObject<Item> appliUnlockedChipShotmob = ITEMS.register("applichip_shotmob_unlocked",()-> new AppliUnlockedChipItem(appliChipShotmob));
    public static final RegistryObject<Item> appliUnlockedChipCardmob = ITEMS.register("applichip_cardmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCardmob));
    public static final RegistryObject<Item> appliUnlockedChipRopuremob = ITEMS.register("applichip_ropuremob_unlocked",()-> new AppliUnlockedChipItem(appliChipRopuremob));
    public static final RegistryObject<Item> appliUnlockedChipPuzzlemob = ITEMS.register("applichip_puzzlemob_unlocked",()-> new AppliUnlockedChipItem(appliChipPuzzlemob));
    public static final RegistryObject<Item> appliUnlockedChipDancemob = ITEMS.register("applichip_dancemob_unlocked",()-> new AppliUnlockedChipItem(appliChipDancemob));
    public static final RegistryObject<Item> appliUnlockedChipRacemob = ITEMS.register("applichip_racemob_unlocked",()-> new AppliUnlockedChipItem(appliChipRacemob));
    public static final RegistryObject<Item> appliUnlockedChipOnmob = ITEMS.register("applichip_onmob_unlocked",()-> new AppliUnlockedChipItem(appliChipOnmob));
    public static final RegistryObject<Item> appliUnlockedChipOffmob = ITEMS.register("applichip_offmob_unlocked",()-> new AppliUnlockedChipItem(appliChipOffmob));
    public static final RegistryObject<Item> appliUnlockedChipV_jumpmob = ITEMS.register("applichip_vjumpmob_unlocked",()-> new AppliUnlockedChipItem(appliChipV_jumpmob));
    public static final RegistryObject<Item> appliUnlockedChipDosukomob = ITEMS.register("applichip_dosukomob_unlocked",()-> new AppliUnlockedChipItem(appliChipDosukomob));
    public static final RegistryObject<Item> appliUnlockedChipBramob = ITEMS.register("applichip_bramob_unlocked",()-> new AppliUnlockedChipItem(appliChipBramob));
    public static final RegistryObject<Item> appliUnlockedChipCoachmob = ITEMS.register("applichip_coachmob_unlocked",()-> new AppliUnlockedChipItem(appliChipCoachmob));
    public static final RegistryObject<Item> appliUnlockedChipGaiamob = ITEMS.register("applichip_gaiamob_unlocked",()-> new AppliUnlockedChipItem(appliChipGaiamob));
    public static final RegistryObject<Item> appliUnlockedChipOujamob = ITEMS.register("applichip_oujamob_unlocked",()-> new AppliUnlockedChipItem(appliChipOujamob));
    public static final RegistryObject<Item> appliUnlockedChipSakusimob = ITEMS.register("applichip_sakusimob_unlocked",()-> new AppliUnlockedChipItem(appliChipSakusimob));
    public static final RegistryObject<Item> appliUnlockedChipUratekumob = ITEMS.register("applichip_uratekumob_unlocked",()-> new AppliUnlockedChipItem(appliChipUratekumob));
    public static final RegistryObject<Item> appliUnlockedChipHadesmob = ITEMS.register("applichip_hadesmob_unlocked",()-> new AppliUnlockedChipItem(appliChipHadesmob));
    public static final RegistryObject<Item> appliUnlockedChipPoseidomob = ITEMS.register("applichip_poseidomob_unlocked",()-> new AppliUnlockedChipItem(appliChipPoseidomob));
    public static final RegistryObject<Item> appliUnlockedChipRebootmob = ITEMS.register("applichip_rebootmob_unlocked",()-> new AppliUnlockedChipItem(appliChipRebootmob));
    public static final RegistryObject<Item> appliUnlockedChipDeusumob = ITEMS.register("applichip_deusumob_unlocked",()-> new AppliUnlockedChipItem(appliChipDeusumob));
    public static final RegistryObject<Item> appliUnlockedChipOuranosmob = ITEMS.register("applichip_ouranosmob_unlocked",()-> new AppliUnlockedChipItem(appliChipOuranosmob));
    public static final RegistryObject<Item> appliUnlockedChipDantemob = ITEMS.register("applichip_dantemob_unlocked",()-> new AppliUnlockedChipItem(appliChipDantemob));
    public static final RegistryObject<Item> appliUnlockedChipFlickmob = ITEMS.register("applichip_flickmob_unlocked",()-> new AppliUnlockedChipItem(appliChipFlickmob));
    public static final RegistryObject<Item> appliUnlockedChipSwipemob = ITEMS.register("applichip_swipemob_unlocked",()-> new AppliUnlockedChipItem(appliChipSwipemob));
    public static final RegistryObject<Item> appliUnlockedChipTapmob = ITEMS.register("applichip_tapmob_unlocked",()-> new AppliUnlockedChipItem(appliChipTapmob));
    public static final RegistryObject<AppmonBand> APPMONBAND = ITEMS.register( "appmon_band", AppmonBand::new);
}


